scalar Buffer

type MEMB_STAT {
  ConnectStat: Int!
}

type Guild {
  G_Name: String!
  G_Mark: Buffer!
  G_Score: Int!
  G_Master: String!
  G_Count: Int!
  Number: Int!
  G_Type: Int!
  G_Rival: Int!
  G_Union: Int!
}

type GuildMember {
  Name: String!
  G_Name: String!
  G_Level: String!
  G_Status: String!
  guild: Guild
}

type Character {
  Name: String!
  cLevel: Int!
  LevelUpPoint: Int!
  Class: Int!
  Experience: Int!
  Strength: Int!
  Dexterity: Int!
  Vitality: Int!
  Energy: Int!
  Leadership: Int!
  Inventory: String!
  Money: Int!
  MapNumber: Int!
  MapPosX: Int!
  MapPosY: Int!
  PkCount: Int!
  CtlCode: Int!
  Resets: Int!
  BanPost: Int!
  IsMarried: Int!
  MarryName: String!
  QuestNumber: Int!
  QuestMonsters: Int!
  QuestInCurse: Int!
  QuestInProgress: Int!
  SkyEventWins: Int!
  IsVip: Int!
  VipExpirationTime: Int!
  status: MEMB_STAT
  guild_member: GuildMember
}

type CharactersResult {
  count: Int
  rows: [Character]
}

type Query {
  character(name: String!): Character
  characters(page: Int, perPage: Int, classes: [Int]): CharactersResult
}
