scalar Buffer

type Guild {
  G_Name: String!
  G_Mark: Buffer!
  G_Score: Int!
  G_Master: String!
  G_Count: Int!
  Number: Int!
  G_Type: Int!
  G_Rival: Int!
  G_Union: Int!
  TotalResets: Int!
  TotalMembers: Int!
}

type GuildMember {
  Name: String!
  G_Name: String!
  G_Level: String!
  G_Status: String!
  guild: Guild
}

type GuildsResult {
  rows: [Guild]
  count: Int
}

type Query {
  guild(name: String!): Guild
  guilds(page: Int, perPage: Int): GuildsResult
}
